# Generated by Django 3.2.9 on 2021-11-13 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название фильма')),
                ('title_eng', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название фильма на англ')),
                ('tagline', models.CharField(blank=True, max_length=300, null=True, verbose_name='Слоган')),
                ('country', models.CharField(max_length=100, null=True, verbose_name='Страна')),
                ('age', models.CharField(max_length=100, null=True, verbose_name='Возраст')),
                ('duration', models.IntegerField(max_length=100, null=True, verbose_name='Длительность(мин)')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='url')),
                ('image', models.ImageField(upload_to='movie_image/', verbose_name='Изображение')),
                ('release_date', models.IntegerField(verbose_name='Год выпуска')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('budget', models.PositiveIntegerField(null=True, verbose_name='Бюджет фильма')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['-is_published'],
            },
        ),
        migrations.CreateModel(
            name='MovieCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Категория')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='url')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='MovieDirectorActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Имя')),
                ('image', models.ImageField(blank=True, null=True, upload_to='director_actor/', verbose_name='Фотография')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Актер и режиссер',
                'verbose_name_plural': 'Актеры и режиссеры',
            },
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Жанр')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='url')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='MovieComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('user_name', models.CharField(max_length=70, verbose_name='Пользователь')),
                ('comment', models.TextField(max_length=3000, verbose_name='Комментарий')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.movie', verbose_name='Фильм')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.moviecomment')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(max_length=50, related_name='movie_actor', to='news.MovieDirectorActor', verbose_name='Актеры'),
        ),
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.moviecategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(max_length=50, related_name='movie_director', to='news.MovieDirectorActor', verbose_name='Режиссер'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='news.MovieGenre', verbose_name='Жанр'),
        ),
    ]
