# Generated by Django 3.2.9 on 2021-11-16 13:58

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20211116_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Описание'),
        ),
    ]
