# Generated by Django 3.2.9 on 2021-11-19 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_movie_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviecomment',
            old_name='user_name',
            new_name='username',
        ),
    ]
