# Generated by Django 3.2.9 on 2021-11-20 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_rename_user_name_moviecomment_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecomment',
            name='comment_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
