# Generated by Django 3.2.9 on 2021-11-21 20:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_moviecomment_comment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='IframeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя фильма')),
                ('iframe', models.TextField(verbose_name='Ссылка на трейлер')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='awards',
            field=models.CharField(max_length=100, null=True, verbose_name='Награды фильма'),
        ),
        migrations.AddField(
            model_name='movie',
            name='premiere_date',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Дата премьеры'),
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(upload_to='photo_gallery/', verbose_name='Фотография')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.movie', verbose_name='Фильм')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='iframe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.iframevideo', verbose_name='Трейлер'),
        ),
    ]
