# Generated by Django 3.2.9 on 2021-11-23 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20211121_2310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iframevideo',
            options={},
        ),
    ]
