# Generated by Django 3.2.9 on 2021-11-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20211123_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iframevideo',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя фильма'),
        ),
    ]
