# Generated by Django 3.2.9 on 2021-11-23 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_alter_iframevideo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iframevideo',
            name='name',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.movie', verbose_name='Имя фильма'),
        ),
    ]
