# Generated by Django 3.2.9 on 2021-12-10 12:53

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_alter_moviecomment_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='awards_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Награды фильма'),
        ),
        migrations.AddField(
            model_name='movie',
            name='awards_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Награды фильма'),
        ),
        migrations.AddField(
            model_name='movie',
            name='country_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='movie',
            name='country_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='movie',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='movie',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tagline_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tagline_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Название фильма'),
        ),
        migrations.AddField(
            model_name='movie',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название фильма'),
        ),
        migrations.AddField(
            model_name='moviecategory',
            name='name_en',
            field=models.CharField(max_length=70, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='moviecategory',
            name='name_ru',
            field=models.CharField(max_length=70, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='moviedirectoractor',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='moviedirectoractor',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='moviedirectoractor',
            name='name_en',
            field=models.CharField(max_length=70, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='moviedirectoractor',
            name='name_ru',
            field=models.CharField(max_length=70, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='moviegenre',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='moviegenre',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
    ]
